/run/verbose 1
/run/initialize
/gun/sourceGen false
/gps/particle gamma
/gps/pos/type   Plane
/gps/pos/shape  Circle
/gps/pos/radius 20 cm
/gps/pos/rot1 1 0 -2.28522e-16
/gps/pos/rot2 -1.63312e+16 1 0
/gps/pos/centre 1.77438e-15 28.9778 7.76457
/gps/direction -2.28522e-16 -3.73205 -1
/gps/ene/type Lin
/gps/ene/min 10 keV
/gps/ene/max 50000 keV
/gps/ene/gradient  0.
/gps/ene/intercept 1.
/run/beamOn 10000
